sudo: required
language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libeigen3-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./test/eigen3-units/test-eigen3-units